apiVersion: v1
kind: Secret
metadata:
  name: openshift-oauth-apiserver
data:
  kubeconfig: {{ pki "internal-admin.kubeconfig" }}
  server.crt: {{ pki "oauth-apiserver-server.crt" }}
  server.key: {{ pki "oauth-apiserver-server.key" }}
  etcd-client.crt: {{ pki "etcd-client.crt" }}
  etcd-client.key: {{ pki "etcd-client.key" }}
